Specify export folder path
dmstr/yii2-contact-module pull request #10
Opened 2023-03-16 12:36 UTC by germanbisurgi

Fixes error "mkdir(): Permission denied" when exporting.

2023-03-16 12:55 UTC, eluhr commented
@handcode: The problem here was that the ExportMenu widget set an incorrect export path.

2023-03-16 12:55 UTC, eluhr approved these changes

2023-03-16 14:29 UTC, handcode requested changes
Being able to set the path is definitely a good idea. But please not with "hardcoded" path definition and especially not in a view. This has to be done e.g. via a module property.

2023-03-17 08:47 UTC, handcode approved these changes

2023-03-17 09:37 UTC, merged